### ISSUE TITLE
HOW DO YOU PLAY THIS GAME

### ISSUE THREAD

**Issue by sewnie** [alpheratz0/xgameoflife#1]
1. this looks really nice i love this program
2. how do i get those weird things to show up so the game can begin, i tried left clicking on the grid and then running it but they just dissapear.

**Comment by sewnie** [comment]
nvm im stupid

**Comment by alpheratz0** [comment]
It's not really a `game`, check https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life

**Comment by sewnie** [comment]
idk it just looks really cool
